using System;
using System.Collections.Generic;
using System.Text;

namespace MorphanBotNetCore.Games.DnD
{
    public class DnDMythWeavers
    {
        public bool Error { get; set; }

        public DnDMWSheetData Sheetdata { get; set; }
    }

    public class DnDMWSheetData
    {
        public int? Id { get; set; }

        public string Name { get; set; }

        public string Portrait { get; set; }

        public int? SheetTemplateId { get; set; }

        public int? GameId { get; set; }

        public int? Private { get; set; }

        public string CreatedAt { get; set; }

        public string UpdatedAt { get; set; }

        public string DeletedAt { get; set; }

        public string DownloadedAt { get; set; }

        public string SheetdataRevisionId { get; set; }

        public DnDMWSheetTemplate SheetTemplate { get; set; }

        public DnDMWJsonSheetData SheetData { get; set; }

        public DnDMWData Data { get; set; }
    }

    public class DnDMWSheetTemplate
    {
        public int? Id { get; set; }

        public string Name { get; set; }

        public string Path { get; set; }

        public int? GameSystemId { get; set; }

        public string CreatedAt { get; set; }

        public string UpdatedAt { get; set; }

        public int? Active { get; set; }
    }

    public class DnDMWJsonSheetData
    {
        public int? Id { get; set; }

        public int? SheetId { get; set; }

        public string Jsondata { get; set; }
    }

    public class DnDMWData
    {
        public string Name { get; set; }
        public string Player { get; set; }
        public string Campaign { get; set; }
        public string Class { get; set; }
        public string Race { get; set; }
        public string Deity { get; set; }
        public string Alignment { get; set; }
        public string Caster { get; set; }
        public string Level { get; set; }
        public string Experience { get; set; }
        public string NextLevel { get; set; }
        public string Background { get; set; }
        public string Inspiration { get; set; }
        public string ProficiencyBonus { get; set; }
        public string Hp { get; set; }
        public string ArmorClass { get; set; }
        public string Initiative { get; set; }
        public string PassivePerception { get; set; }
        public string Speed { get; set; }
        public string HeavyArmor { get; set; }
        public string Mph { get; set; }
        public string Mpd { get; set; }
        public string Strength { get; set; }
        public string StrengthMod { get; set; }
        public string StrengthSave { get; set; }
        public string DexteritySave { get; set; }
        public string ConstitutionSave { get; set; }
        public string IntelligenceSave { get; set; }
        public string AthleticsMod { get; set; }
        public string Dexterity { get; set; }
        public string DexterityMod { get; set; }
        public string AcrobaticsMod { get; set; }
        public string SleightOfHandMod { get; set; }
        public string StealthMod { get; set; }
        public string Constitution { get; set; }
        public string ConstitutionMod { get; set; }
        public string Intelligence { get; set; }
        public string IntelligenceMod { get; set; }
        public string ArcanaMod { get; set; }
        public string HistoryMod { get; set; }
        public string InvestigationMod { get; set; }
        public string NatureMod { get; set; }
        public string ReligionMod { get; set; }
        public string Wisdom { get; set; }
        public string WisdomMod { get; set; }
        public string WisdomSave { get; set; }
        public string AnimalHandlingMod { get; set; }
        public string InsightMod { get; set; }
        public string MedicineMod { get; set; }
        public string PerceptionMod { get; set; }
        public string SurvivalMod { get; set; }
        public string Charisma { get; set; }
        public string CharismaMod { get; set; }
        public string CharismaSave { get; set; }
        public string DeceptionMod { get; set; }
        public string IntimidationMod { get; set; }
        public string PerformanceMod { get; set; }
        public string PersuasionMod { get; set; }
        public string AthleticsCc { get; set; }
        public string AcrobaticsCc { get; set; }
        public string SleightOfHandCc { get; set; }
        public string StealthCc { get; set; }
        public string ArcanaCc { get; set; }
        public string HistoryCc { get; set; }
        public string InvestigationCc { get; set; }
        public string NatureCc { get; set; }
        public string ReligionCc { get; set; }
        public string AnimalHandlingCc { get; set; }
        public string InsightCc { get; set; }
        public string MedicineCc { get; set; }
        public string PerceptionCc { get; set; }
        public string SurvivalCc { get; set; }
        public string DeceptionCc { get; set; }
        public string IntimidationCc { get; set; }
        public string PerformanceCc { get; set; }
        public string PersuasionCc { get; set; }
        public string CharismaSaveCc { get; set; }
        public string WisdomSaveCc { get; set; }
        public string IntelligenceSaveCc { get; set; }
        public string ConstitutionSaveCc { get; set; }
        public string DexteritySaveCc { get; set; }
        public string StrengthSaveCc { get; set; }
        public string Proficiency1 { get; set; }
        public string Proficiency2 { get; set; }
        public string Proficiency3 { get; set; }
        public string Proficiency4 { get; set; }
        public string Proficiency5 { get; set; }
        public string Proficiency6 { get; set; }
        public string Proficiency7 { get; set; }
        public string Proficiency8 { get; set; }
        public string Proficiency9 { get; set; }
        public string Proficiency10 { get; set; }
        public string Proficiency11 { get; set; }
        public string Proficiency12 { get; set; }
        public string DeathsavesSuccesses { get; set; }
        public string DeathsavesFailures { get; set; }
        public string TempHp { get; set; }
        public string MaxHp { get; set; }
        public string HitDice { get; set; }
        public string __TxtPersonality { get; set; }
        public string __TxtIdeals { get; set; }
        public string __TxtBonds { get; set; }
        public string __TxtFlaws { get; set; }
        public string __TxtFeaturesTraits { get; set; }
        public string Weapon1Name { get; set; }
        public string Weapon1Attack { get; set; }
        public string Weapon1Dmg { get; set; }
        public string Weapon2Name { get; set; }
        public string Weapon3Name { get; set; }
        public string Weapon4Name { get; set; }
        public string Weapon5Name { get; set; }
        public string Weapon2Attack { get; set; }
        public string Weapon3Attack { get; set; }
        public string Weapon4Attack { get; set; }
        public string Weapon5Attack { get; set; }
        public string Weapon2Dmg { get; set; }
        public string Weapon3Dmg { get; set; }
        public string Weapon4Dmg { get; set; }
        public string Weapon5Dmg { get; set; }
        public string AdventurersPack { get; set; }
        public string Equip1_ { get; set; }
        public string Equip2_ { get; set; }
        public string Equip3_ { get; set; }
        public string Equip4_ { get; set; }
        public string Equip5_ { get; set; }
        public string Equip6_ { get; set; }
        public string Equip7_ { get; set; }
        public string Equip8_ { get; set; }
        public string Equip9_ { get; set; }
        public string Equip10_ { get; set; }
        public string Equip11_ { get; set; }
        public string Equip12_ { get; set; }
        public string Equip13_ { get; set; }
        public string Equip14_ { get; set; }
        public string Equip15_ { get; set; }
        public string Equip16_ { get; set; }
        public string Equip17_ { get; set; }
        public string Equip18_ { get; set; }
        public string Equip19_ { get; set; }
        public string Equip20_ { get; set; }
        public string Equip1Weight { get; set; }
        public string Equip1Worth { get; set; }
        public string Equip1Loc { get; set; }
        public string Equip2Weight { get; set; }
        public string Equip2Worth { get; set; }
        public string Equip2Loc { get; set; }
        public string Equip3Weight { get; set; }
        public string Equip3Worth { get; set; }
        public string Equip3Loc { get; set; }
        public string Equip4Weight { get; set; }
        public string Equip4Worth { get; set; }
        public string Equip4Loc { get; set; }
        public string Equip5Weight { get; set; }
        public string Equip5Worth { get; set; }
        public string Equip5Loc { get; set; }
        public string Equip6Weight { get; set; }
        public string Equip6Worth { get; set; }
        public string Equip6Loc { get; set; }
        public string Equip7Weight { get; set; }
        public string Equip7Worth { get; set; }
        public string Equip7Loc { get; set; }
        public string Equip8Weight { get; set; }
        public string Equip8Worth { get; set; }
        public string Equip8Loc { get; set; }
        public string Equip9Weight { get; set; }
        public string Equip9Worth { get; set; }
        public string Equip9Loc { get; set; }
        public string Equip10Weight { get; set; }
        public string Equip10Worth { get; set; }
        public string Equip10Loc { get; set; }
        public string Equip11Weight { get; set; }
        public string Equip11Worth { get; set; }
        public string Equip11Loc { get; set; }
        public string Equip12Weight { get; set; }
        public string Equip12Worth { get; set; }
        public string Equip12Loc { get; set; }
        public string Equip13Weight { get; set; }
        public string Equip13Worth { get; set; }
        public string Equip13Loc { get; set; }
        public string Equip14Weight { get; set; }
        public string Equip14Worth { get; set; }
        public string Equip14Loc { get; set; }
        public string Equip15Weight { get; set; }
        public string Equip15Worth { get; set; }
        public string Equip15Loc { get; set; }
        public string Equip16Weight { get; set; }
        public string Equip16Worth { get; set; }
        public string Equip16Loc { get; set; }
        public string Equip17Weight { get; set; }
        public string Equip17Worth { get; set; }
        public string Equip17Loc { get; set; }
        public string Equip18Weight { get; set; }
        public string Equip18Worth { get; set; }
        public string Equip18Loc { get; set; }
        public string Equip19Weight { get; set; }
        public string Equip19Worth { get; set; }
        public string Equip19Loc { get; set; }
        public string Equip20Weight { get; set; }
        public string Equip20Worth { get; set; }
        public string Equip20Loc { get; set; } 
        public string CurrencyCp { get; set; }
        public string CurrencySp { get; set; }
        public string CurrencyEp { get; set; }
        public string CurrencyGp { get; set; }
        public string CurrencyPp { get; set; }
        public string CastingAbility { get; set; }
        public string SaveDc { get; set; }
        public string AttackBonus { get; set; }
        public string Spell_0_1 { get; set; }
        public string Spell_0_2 { get; set; }
        public string Spell_0_3 { get; set; }
        public string Spell_0_4 { get; set; }
        public string Spell_0_5 { get; set; }
        public string Spell_0_6 { get; set; }
        public string Spell_0_7 { get; set; }
        public string Spell_0_8 { get; set; }
        public string Spell_0_9 { get; set; }
        public string Spell_0_10 { get; set; }
        public string Spell_0_11 { get; set; }
        public string Spell_0_12 { get; set; }
        public string Spell_0_13 { get; set; }
        public string Spell_0_14 { get; set; }
        public string Spell_0_15 { get; set; }
        public string Spell_0_16 { get; set; }
        public string Spell_1_1 { get; set; }
        public string Spell_1_2 { get; set; }
        public string Spell_1_3 { get; set; }
        public string Spell_1_4 { get; set; }
        public string Spell_1_5 { get; set; }
        public string Spell_1_6 { get; set; }
        public string Spell_1_7 { get; set; }
        public string Spell_1_8 { get; set; }
        public string Spell_1_9 { get; set; }
        public string Spell_1_10 { get; set; }
        public string Spell_1_11 { get; set; }
        public string Spell_1_12 { get; set; }
        public string Spell_1_13 { get; set; }
        public string Spell_2_1 { get; set; }
        public string Spell_2_2 { get; set; }
        public string Spell_2_3 { get; set; }
        public string Spell_2_4 { get; set; }
        public string Spell_2_5 { get; set; }
        public string Spell_2_6 { get; set; }
        public string Spell_2_7 { get; set; }
        public string Spell_2_8 { get; set; }
        public string Spell_2_9 { get; set; }
        public string Spell_2_10 { get; set; }
        public string Spell_2_11 { get; set; }
        public string Spell_2_12 { get; set; }
        public string Spell_2_13 { get; set; }
        public string Spell_3_1 { get; set; }
        public string Spell_3_2 { get; set; }
        public string Spell_3_3 { get; set; }
        public string Spell_3_4 { get; set; }
        public string Spell_3_5 { get; set; }
        public string Spell_3_6 { get; set; }
        public string Spell_3_7 { get; set; }
        public string Spell_3_8 { get; set; }
        public string Spell_3_9 { get; set; }
        public string Spell_3_10 { get; set; }
        public string Spell_3_11 { get; set; }
        public string Spell_3_12 { get; set; }
        public string Spell_3_13 { get; set; }
        public string Spell_4_1 { get; set; }
        public string Spell_4_2 { get; set; }
        public string Spell_4_3 { get; set; }
        public string Spell_4_4 { get; set; }
        public string Spell_4_5 { get; set; }
        public string Spell_4_6 { get; set; }
        public string Spell_4_7 { get; set; }
        public string Spell_4_8 { get; set; }
        public string Spell_4_9 { get; set; }
        public string Spell_4_10 { get; set; }
        public string Spell_4_11 { get; set; }
        public string Spell_4_12 { get; set; }
        public string Spell_4_13 { get; set; }
        public string Spell_5_1 { get; set; }
        public string Spell_5_2 { get; set; }
        public string Spell_5_3 { get; set; }
        public string Spell_5_4 { get; set; }
        public string Spell_5_5 { get; set; }
        public string Spell_5_6 { get; set; }
        public string Spell_5_7 { get; set; }
        public string Spell_5_8 { get; set; }
        public string Spell_5_9 { get; set; }
        public string Spell_5_10 { get; set; }
        public string Spell_5_11 { get; set; }
        public string Spell_5_12 { get; set; }
        public string Spell_5_13 { get; set; }
        public string Spell_6_1 { get; set; }
        public string Spell_6_2 { get; set; }
        public string Spell_6_3 { get; set; }
        public string Spell_6_4 { get; set; }
        public string Spell_6_5 { get; set; }
        public string Spell_6_6 { get; set; }
        public string Spell_6_7 { get; set; }
        public string Spell_6_8 { get; set; }
        public string Spell_6_9 { get; set; }
        public string Spell_6_10 { get; set; }
        public string Spell_6_11 { get; set; }
        public string Spell_6_12 { get; set; }
        public string Spell_6_13 { get; set; }
        public string Spell_7_1 { get; set; }
        public string Spell_7_2 { get; set; }
        public string Spell_7_3 { get; set; }
        public string Spell_7_4 { get; set; }
        public string Spell_7_5 { get; set; }
        public string Spell_7_6 { get; set; }
        public string Spell_7_7 { get; set; }
        public string Spell_7_8 { get; set; }
        public string Spell_7_9 { get; set; }
        public string Spell_7_10 { get; set; }
        public string Spell_7_11 { get; set; }
        public string Spell_7_12 { get; set; }
        public string Spell_7_13 { get; set; }
        public string Spell_8_1 { get; set; }
        public string Spell_8_2 { get; set; }
        public string Spell_8_3 { get; set; }
        public string Spell_8_4 { get; set; }
        public string Spell_8_5 { get; set; }
        public string Spell_8_6 { get; set; }
        public string Spell_8_7 { get; set; }
        public string Spell_8_8 { get; set; }
        public string Spell_8_9 { get; set; }
        public string Spell_8_10 { get; set; }
        public string Spell_8_11 { get; set; }
        public string Spell_8_12 { get; set; }
        public string Spell_8_13 { get; set; }
        public string Spell_9_1 { get; set; }
        public string Spell_9_2 { get; set; }
        public string Spell_9_3 { get; set; }
        public string Spell_9_4 { get; set; }
        public string Spell_9_5 { get; set; }
        public string Spell_9_6 { get; set; }
        public string Spell_9_7 { get; set; }
        public string Spell_9_8 { get; set; }
        public string Spell_9_9 { get; set; }
        public string Spell_9_10 { get; set; }
        public string Spell_9_11 { get; set; }
        public string Spell_9_12 { get; set; }
        public string Spell_9_13 { get; set; }
        public string Spell_0_1Mem { get; set; }
        public string Spell_0_2Mem { get; set; }
        public string Spell_0_3Mem { get; set; }
        public string Spell_0_4Mem { get; set; }
        public string Spell_0_5Mem { get; set; }
        public string Spell_0_6Mem { get; set; }
        public string Spell_0_7Mem { get; set; }
        public string Spell_0_8Mem { get; set; }
        public string Spell_0_9Mem { get; set; }
        public string Spell_0_10Mem { get; set; }
        public string Spell_0_11Mem { get; set; }
        public string Spell_0_12Mem { get; set; }
        public string Spell_0_13Mem { get; set; }
        public string Spell_0_14Mem { get; set; }
        public string Spell_0_15Mem { get; set; }
        public string Spell_0_16Mem { get; set; }
        public string Spell_1_1Mem { get; set; }
        public string Spell_1_2Mem { get; set; }
        public string Spell_1_3Mem { get; set; }
        public string Spell_1_4Mem { get; set; }
        public string Spell_1_5Mem { get; set; }
        public string Spell_1_6Mem { get; set; }
        public string Spell_1_7Mem { get; set; }
        public string Spell_1_8Mem { get; set; }
        public string Spell_1_9Mem { get; set; }
        public string Spell_1_10Mem { get; set; }
        public string Spell_1_11Mem { get; set; }
        public string Spell_1_12Mem { get; set; }
        public string Spell_1_13Mem { get; set; }
        public string Spell_2_1Mem { get; set; }
        public string Spell_2_2Mem { get; set; }
        public string Spell_2_3Mem { get; set; }
        public string Spell_2_4Mem { get; set; }
        public string Spell_2_5Mem { get; set; }
        public string Spell_2_6Mem { get; set; }
        public string Spell_2_7Mem { get; set; }
        public string Spell_2_8Mem { get; set; }
        public string Spell_2_9Mem { get; set; }
        public string Spell_2_10Mem { get; set; }
        public string Spell_2_11Mem { get; set; }
        public string Spell_2_12Mem { get; set; }
        public string Spell_2_13Mem { get; set; }
        public string Spell_3_1Mem { get; set; }
        public string Spell_3_2Mem { get; set; }
        public string Spell_3_3Mem { get; set; }
        public string Spell_3_4Mem { get; set; }
        public string Spell_3_5Mem { get; set; }
        public string Spell_3_6Mem { get; set; }
        public string Spell_3_7Mem { get; set; }
        public string Spell_3_8Mem { get; set; }
        public string Spell_3_9Mem { get; set; }
        public string Spell_3_10Mem { get; set; }
        public string Spell_3_11Mem { get; set; }
        public string Spell_3_12Mem { get; set; }
        public string Spell_3_13Mem { get; set; }
        public string Spell_4_1Mem { get; set; }
        public string Spell_4_2Mem { get; set; }
        public string Spell_4_3Mem { get; set; }
        public string Spell_4_4Mem { get; set; }
        public string Spell_4_5Mem { get; set; }
        public string Spell_4_6Mem { get; set; }
        public string Spell_4_7Mem { get; set; }
        public string Spell_4_8Mem { get; set; }
        public string Spell_4_9Mem { get; set; }
        public string Spell_4_10Mem { get; set; }
        public string Spell_4_11Mem { get; set; }
        public string Spell_4_12Mem { get; set; }
        public string Spell_4_13Mem { get; set; }
        public string Spell_5_1Mem { get; set; }
        public string Spell_5_2Mem { get; set; }
        public string Spell_5_3Mem { get; set; }
        public string Spell_5_4Mem { get; set; }
        public string Spell_5_5Mem { get; set; }
        public string Spell_5_6Mem { get; set; }
        public string Spell_5_7Mem { get; set; }
        public string Spell_5_8Mem { get; set; }
        public string Spell_5_9Mem { get; set; }
        public string Spell_5_10Mem { get; set; }
        public string Spell_5_11Mem { get; set; }
        public string Spell_5_12Mem { get; set; }
        public string Spell_5_13Mem { get; set; }
        public string Spell_6_1Mem { get; set; }
        public string Spell_6_2Mem { get; set; }
        public string Spell_6_3Mem { get; set; }
        public string Spell_6_4Mem { get; set; }
        public string Spell_6_5Mem { get; set; }
        public string Spell_6_6Mem { get; set; }
        public string Spell_6_7Mem { get; set; }
        public string Spell_6_8Mem { get; set; }
        public string Spell_6_9Mem { get; set; }
        public string Spell_6_10Mem { get; set; }
        public string Spell_6_11Mem { get; set; }
        public string Spell_6_12Mem { get; set; }
        public string Spell_6_13Mem { get; set; }
        public string Spell_7_1Mem { get; set; }
        public string Spell_7_2Mem { get; set; }
        public string Spell_7_3Mem { get; set; }
        public string Spell_7_4Mem { get; set; }
        public string Spell_7_5Mem { get; set; }
        public string Spell_7_6Mem { get; set; }
        public string Spell_7_7Mem { get; set; }
        public string Spell_7_8Mem { get; set; }
        public string Spell_7_9Mem { get; set; }
        public string Spell_7_10Mem { get; set; }
        public string Spell_7_11Mem { get; set; }
        public string Spell_7_12Mem { get; set; }
        public string Spell_7_13Mem { get; set; }
        public string Spell_8_1Mem { get; set; }
        public string Spell_8_2Mem { get; set; }
        public string Spell_8_3Mem { get; set; }
        public string Spell_8_4Mem { get; set; }
        public string Spell_8_5Mem { get; set; }
        public string Spell_8_6Mem { get; set; }
        public string Spell_8_7Mem { get; set; }
        public string Spell_8_8Mem { get; set; }
        public string Spell_8_9Mem { get; set; }
        public string Spell_8_10Mem { get; set; }
        public string Spell_8_11Mem { get; set; }
        public string Spell_8_12Mem { get; set; }
        public string Spell_8_13Mem { get; set; }
        public string Spell_9_1Mem { get; set; }
        public string Spell_9_2Mem { get; set; }
        public string Spell_9_3Mem { get; set; }
        public string Spell_9_4Mem { get; set; }
        public string Spell_9_5Mem { get; set; }
        public string Spell_9_6Mem { get; set; }
        public string Spell_9_7Mem { get; set; }
        public string Spell_9_8Mem { get; set; }
        public string Spell_9_9Mem { get; set; }
        public string Spell_9_10Mem { get; set; }
        public string Spell_9_11Mem { get; set; }
        public string Spell_9_12Mem { get; set; }
        public string Spell_9_13Mem { get; set; }
        public string Spell_1Prepared { get; set; }
        public string Spell_1Slots { get; set; }
        public string Spell_1SlotsLeft { get; set; }
        public string Spell_2Prepared { get; set; }
        public string Spell_2Slots { get; set; }
        public string Spell_2SlotsLeft { get; set; }
        public string Spell_3Prepared { get; set; }
        public string Spell_3Slots { get; set; }
        public string Spell_3SlotsLeft { get; set; }
        public string Spell_4Prepared { get; set; }
        public string Spell_4Slots { get; set; }
        public string Spell_4SlotsLeft { get; set; }
        public string Spell_5Prepared { get; set; }
        public string Spell_5Slots { get; set; }
        public string Spell_5SlotsLeft { get; set; }
        public string Spell_6Prepared { get; set; }
        public string Spell_6Slots { get; set; }
        public string Spell_6SlotsLeft { get; set; }
        public string Spell_7Prepared { get; set; }
        public string Spell_7Slots { get; set; }
        public string Spell_7SlotsLeft { get; set; }
        public string Spell_8Prepared { get; set; }
        public string Spell_8Slots { get; set; }
        public string Spell_8SlotsLeft { get; set; }
        public string Spell_9Prepared { get; set; }
        public string Spell_9Slots { get; set; }
        public string Spell_9SlotsLeft { get; set; }
        public string CharacterPortrait { get; set; }
        public string Height { get; set; }
        public string Weight { get; set; }
        public string Age { get; set; }
        public string Gender { get; set; }
        public string Hair { get; set; }
        public string HairColor { get; set; }
        public string Eyes { get; set; }
        public string Skin { get; set; }
        public string EyesColor { get; set; }
        public string SkinColor { get; set; }
        public string Language_1 { get; set; }
        public string Language_2 { get; set; }
        public string Language_3 { get; set; }
        public string Language_4 { get; set; }
        public string Language_5 { get; set; }
        public string Language_6 { get; set; }
        public string Language_7 { get; set; }
        public string Language_8 { get; set; }
        public string Language_9 { get; set; }
        public string Language_10 { get; set; }
        public string Language_11 { get; set; }
        public string Language_12 { get; set; }
        public string Language_13 { get; set; }
        public string Language_14 { get; set; }
        public string __TxtCharacter_1Name { get; set; }
        public string __TxtCharacter_1 { get; set; }
        public string __TxtCharacter_2Name { get; set; }
        public string __TxtCharacter_2 { get; set; }
        public string __TxtCharacter_3Name { get; set; }
        public string __TxtCharacter_3 { get; set; }
        public string __TxtCharacter_4Name { get; set; }
        public string __TxtCharacter_4 { get; set; }
        public string __TxtCharacter_5Name { get; set; }
        public string __TxtCharacter_5 { get; set; }
        public string __TxtCharacter_6Name { get; set; }
        public string __TxtCharacter_6 { get; set; }
        public string __TxtStatblock { get; set; }
        public string __TxtOtherNotes { get; set; }
        public string __TxtPrivateNotes { get; set; }
        public string _MetaSheetDataVersion { get; set; }
    }
}
